### ISSUE TITLE
hcclient is a package

### ISSUE THREAD

**Issue by serangelicloud** [AnnikaV9/hcclient#8]
when executing `python  -m hcclient --help` im getting an error message saying that it is a package and so it cannot be executed

**To Reproduce**
1. I installed the library through pip using `pip install hcclient`
2. Then i tried executing it using `python -m hcclient --help`
3. this was the output: ``` No module named hcclient.__main__; 'hcclient' is a package and cannot be directly executed```

**Environment>**
 - Operating system: windows 11 
 - Terminal emulator: windows terminal 
 - hcclient version: 1.19.3
 - Python version: 3.11.8

**Comment by serangelicloud** [comment]
I also just tried locally executing it like this: `python src\hcclient -c testing -n test` and i got this output : `can't find '__main__' module in 'C:\\Users\\Francesco\\Desktop\\hcclient-1.19.3\\src\\hcclient'`


![image](https://github.com/AnnikaV9/hcclient/assets/138161359/eeffba4f-086e-45c5-bb2b-50de7a35f30a)

**Comment by AnnikaV9** [comment]
Simply run it as `hcclient`, not as `python -m hcclient`
Alternatively, use [pipx](https://github.com/pypa/pipx) for installation if you don't want to deal with adding packages to path manually

As for executing in a dev environment, use poetry (See [CONTRIBUTING.md](https://github.com/AnnikaV9/hcclient/blob/master/docs/CONTRIBUTING.md#development-setup))
